# ============================================================
#  database.py — Analysis Items Registry
#  Single source of truth for all 115+ check definitions.
#  Each entry describes one measurable website property.
# ============================================================

ANALYSIS_DB = {
    # ── Performance ──────────────────────────────────────────
    "lcp": {
        "name": "Largest Contentful Paint", "description": "Time when main content loads",
        "details": "LCP measures when the largest content element becomes visible.",
        "impact": "Slow LCP increases bounce rates by up to 32%.",
        "range": "Good: < 2.5s | Poor: > 4.0s",
        "threshold_good": 2500, "threshold_poor": 4000,
        "category": "performance", "priority": "critical",
        "action": "Optimize images, implement lazy loading.", "effort": "medium", "time": "2-4 hours",
    },
    "fid": {
        "name": "First Input Delay", "description": "Time from user interaction to browser response",
        "details": "FID measures the time from when a user first interacts with a page to when the browser can respond.",
        "impact": "High FID frustrates users trying to click buttons.",
        "range": "Good: < 100ms | Poor: > 300ms",
        "threshold_good": 100, "threshold_poor": 300,
        "category": "performance", "priority": "critical",
        "action": "Minimize JavaScript, break up long tasks.", "effort": "medium", "time": "3-6 hours",
    },
    "cls": {
        "name": "Cumulative Layout Shift", "description": "Visual stability score",
        "details": "CLS measures unexpected layout shifts during page lifespan.",
        "impact": "High CLS causes accidental clicks.",
        "range": "Good: < 0.1 | Poor: > 0.25",
        "threshold_good": 0.1, "threshold_poor": 0.25,
        "category": "performance", "priority": "critical",
        "action": "Set explicit dimensions for images.", "effort": "low", "time": "1-2 hours",
    },
    "ttfb": {
        "name": "Time to First Byte", "description": "Server response time",
        "details": "TTFB measures time between request and first byte from server.",
        "impact": "Slow TTFB indicates hosting issues.",
        "range": "Good: < 200ms | Poor: > 600ms",
        "threshold_good": 200, "threshold_poor": 600,
        "category": "performance", "priority": "high",
        "action": "Use CDN, optimize server.", "effort": "medium", "time": "4-8 hours",
    },
    "fcp": {
        "name": "First Contentful Paint", "description": "Time when first content appears",
        "details": "FCP measures when first text or image becomes visible.",
        "impact": "First impression of loading speed.",
        "range": "Good: < 1.8s | Poor: > 3.0s",
        "threshold_good": 1800, "threshold_poor": 3000,
        "category": "performance", "priority": "high",
        "action": "Eliminate render-blocking resources.", "effort": "medium", "time": "2-4 hours",
    },
    "performance_score": {
        "name": "Performance Score", "description": "Overall performance score",
        "details": "Composite score based on all performance checks.",
        "impact": "Higher scores correlate with better UX.",
        "range": "Good: > 90 | Poor: < 50",
        "category": "performance", "priority": "high",
        "action": "Improve individual performance items.", "effort": "varies", "time": "varies",
    },
    "dom_size": {
        "name": "DOM Size", "description": "Number of DOM elements",
        "details": "Total number of elements in the document.",
        "impact": "Excessive DOM elements slow down rendering.",
        "range": "Good: < 800 | Poor: > 1500",
        "threshold_good": 800, "threshold_poor": 1500,
        "category": "performance", "priority": "medium",
        "action": "Simplify HTML structure.", "effort": "medium", "time": "2-4 hours",
    },
    "request_count": {
        "name": "Request Count", "description": "Number of HTTP requests",
        "details": "Total number of resources loaded.",
        "impact": "Too many requests slow page load.",
        "range": "Good: < 50 | Poor: > 100",
        "threshold_good": 50, "threshold_poor": 100,
        "category": "performance", "priority": "medium",
        "action": "Combine files, use CSS sprites.", "effort": "medium", "time": "2-3 hours",
    },
    "page_size": {
        "name": "Page Size", "description": "Total page weight",
        "details": "Total size of all resources in bytes.",
        "impact": "Large pages load slowly on mobile.",
        "range": "Good: < 2MB | Poor: > 5MB",
        "threshold_good": 2_000_000, "threshold_poor": 5_000_000,
        "category": "performance", "priority": "medium",
        "action": "Compress images, minify code.", "effort": "medium", "time": "2-4 hours",
    },

    # ── Security ─────────────────────────────────────────────
    "ssl_days_left": {
        "name": "SSL Certificate Validity", "description": "Days until SSL expires",
        "details": "Days remaining before SSL certificate expires.",
        "impact": "Expired certificates cause browser security warnings.",
        "range": "Good: > 90 days | Poor: < 30 days",
        "threshold_good": 90, "threshold_poor": 30,
        "category": "security", "priority": "critical",
        "action": "Renew SSL certificate before expiry.", "effort": "low", "time": "15 minutes",
    },
    "tls_version": {
        "name": "TLS Protocol Version", "description": "Encryption protocol version",
        "details": "TLS version used for HTTPS connections.",
        "impact": "Older versions have known vulnerabilities.",
        "range": "Good: TLS 1.3 | Poor: TLS 1.0/1.1",
        "category": "security", "priority": "high",
        "action": "Enable TLS 1.3, disable older versions.", "effort": "low", "time": "30 minutes",
    },
    "hsts": {
        "name": "HSTS Enabled", "description": "HTTP Strict Transport Security",
        "details": "HSTS forces browsers to use HTTPS.",
        "impact": "Prevents SSL stripping attacks.",
        "range": "Good: Enabled | Poor: Missing",
        "category": "security", "priority": "high",
        "action": "Enable HSTS with includeSubDomains.", "effort": "low", "time": "15 minutes",
    },
    "csp": {
        "name": "Content Security Policy", "description": "CSP Headers",
        "details": "CSP prevents XSS and data injection attacks.",
        "impact": "Critical protection against XSS attacks.",
        "range": "Good: Enabled | Poor: Missing",
        "category": "security", "priority": "critical",
        "action": "Implement strong Content Security Policy.", "effort": "high", "time": "4-8 hours",
    },
    "xfo": {
        "name": "X-Frame-Options", "description": "Clickjacking protection",
        "details": "Prevents site from being embedded in iframes.",
        "impact": "Protects against clickjacking attacks.",
        "range": "Good: Enabled | Poor: Missing",
        "category": "security", "priority": "medium",
        "action": "Set X-Frame-Options to DENY.", "effort": "low", "time": "10 minutes",
    },
    "xss_protection": {
        "name": "XSS Protection Header", "description": "X-XSS-Protection header",
        "details": "Browser-level XSS filtering hint.",
        "impact": "Legacy browsers benefit from this header.",
        "range": "Good: Enabled | Poor: Missing",
        "category": "security", "priority": "medium",
        "action": "Add X-XSS-Protection: 1; mode=block header.", "effort": "low", "time": "10 minutes",
    },
    "content_type": {
        "name": "X-Content-Type-Options", "description": "MIME sniffing protection",
        "details": "Prevents browsers from MIME-sniffing.",
        "impact": "Reduces drive-by download attacks.",
        "range": "Good: Enabled | Poor: Missing",
        "category": "security", "priority": "medium",
        "action": "Add X-Content-Type-Options: nosniff header.", "effort": "low", "time": "10 minutes",
    },
    "referrer_policy": {
        "name": "Referrer Policy", "description": "Referrer information control",
        "details": "Controls how much referrer info is sent.",
        "impact": "Protects user privacy and sensitive URLs.",
        "range": "Good: Enabled | Poor: Missing",
        "category": "security", "priority": "low",
        "action": "Set Referrer-Policy header.", "effort": "low", "time": "10 minutes",
    },
    "cookies_secure": {
        "name": "Secure Cookies", "description": "Cookies with Secure flag",
        "details": "Whether cookies have the Secure attribute.",
        "impact": "Prevents cookies being sent over HTTP.",
        "range": "Good: Yes | Poor: No",
        "category": "security", "priority": "high",
        "action": "Set Secure flag on all cookies.", "effort": "low", "time": "30 minutes",
    },
    "cookies_httponly": {
        "name": "HttpOnly Cookies", "description": "Cookies with HttpOnly flag",
        "details": "Whether cookies have the HttpOnly attribute.",
        "impact": "Prevents JavaScript from reading cookies.",
        "range": "Good: Yes | Poor: No",
        "category": "security", "priority": "high",
        "action": "Set HttpOnly flag on session cookies.", "effort": "low", "time": "30 minutes",
    },
    "cookies_samesite": {
        "name": "SameSite Cookies", "description": "Cookies with SameSite flag",
        "details": "Whether cookies have the SameSite attribute.",
        "impact": "Mitigates CSRF attacks.",
        "range": "Good: Yes | Poor: No",
        "category": "security", "priority": "medium",
        "action": "Set SameSite=Lax or Strict on cookies.", "effort": "low", "time": "30 minutes",
    },

    # ── Safety ────────────────────────────────────────────────
    "malware_detected": {
        "name": "Malware Detection", "description": "Malware presence on site",
        "details": "Whether malware has been detected by Google Safe Browsing.",
        "impact": "Malware warnings destroy user trust instantly.",
        "range": "Good: None | Poor: Detected",
        "category": "safety", "priority": "critical",
        "action": "Immediately remove malware and request review.", "effort": "high", "time": "8-24 hours",
    },
    "phishing_detected": {
        "name": "Phishing Detection", "description": "Phishing activity on site",
        "details": "Whether site is flagged for phishing.",
        "impact": "Phishing sites are blocked by all major browsers.",
        "range": "Good: None | Poor: Detected",
        "category": "safety", "priority": "critical",
        "action": "Remove phishing content and request review.", "effort": "high", "time": "4-12 hours",
    },
    "unwanted_software": {
        "name": "Unwanted Software", "description": "Unwanted software distribution",
        "details": "Whether site distributes unwanted software.",
        "impact": "Triggers browser warnings and search penalties.",
        "range": "Good: None | Poor: Detected",
        "category": "safety", "priority": "critical",
        "action": "Remove unwanted software and request review.", "effort": "high", "time": "4-12 hours",
    },
    "harmful_apps": {
        "name": "Harmful Applications", "description": "Potentially harmful app distribution",
        "details": "Whether site distributes potentially harmful apps.",
        "impact": "Triggers browser warnings.",
        "range": "Good: None | Poor: Detected",
        "category": "safety", "priority": "critical",
        "action": "Remove harmful content immediately.", "effort": "high", "time": "4-8 hours",
    },
    "social_engineering": {
        "name": "Social Engineering", "description": "Deceptive/phishing content",
        "details": "Whether site uses social engineering tactics.",
        "impact": "Can lead to user data theft.",
        "range": "Good: None | Poor: Detected",
        "category": "safety", "priority": "critical",
        "action": "Remove deceptive content immediately.", "effort": "high", "time": "4-8 hours",
    },
    "safe_browsing_score": {
        "name": "Safe Browsing Score", "description": "Google Safe Browsing status",
        "details": "Composite score from Google Safe Browsing checks.",
        "impact": "Higher score means safer site.",
        "range": "Good: 100 | Poor: 0",
        "category": "safety", "priority": "critical",
        "action": "Remove malicious content and submit for review.", "effort": "high", "time": "varies",
    },
    "blacklist_status": {
        "name": "Blacklist Status", "description": "Whether domain is blacklisted",
        "details": "Check if domain appears on any known blacklists.",
        "impact": "Blacklisted sites lose traffic and email deliverability.",
        "range": "Good: Clean | Poor: Blacklisted",
        "category": "safety", "priority": "critical",
        "action": "Request removal from blacklists.", "effort": "medium", "time": "1-7 days",
    },
    "spam_score": {
        "name": "Spam Score", "description": "Likelihood of being spam",
        "details": "Score indicating how likely the site is considered spam.",
        "impact": "High spam score affects email deliverability.",
        "range": "Good: 0 | Poor: > 5",
        "threshold_good": 0, "threshold_poor": 5,
        "category": "safety", "priority": "high",
        "action": "Remove spammy content and backlinks.", "effort": "medium", "time": "2-4 hours",
    },
    "adult_content": {
        "name": "Adult Content", "description": "Presence of adult content",
        "details": "Whether the site contains adult content.",
        "impact": "May affect safe search filtering.",
        "range": "Good: None | Poor: Present",
        "category": "safety", "priority": "medium",
        "action": "Add age verification if needed.", "effort": "low", "time": "1-2 hours",
    },

    # ── Infrastructure ────────────────────────────────────────
    "dns_time_ms": {
        "name": "DNS Resolution Time", "description": "Time to resolve DNS",
        "details": "Time taken to resolve domain name.",
        "impact": "Slow DNS adds latency before any content loads.",
        "range": "Good: < 50ms | Poor: > 200ms",
        "threshold_good": 50, "threshold_poor": 200,
        "category": "infrastructure", "priority": "medium",
        "action": "Use a faster DNS provider (e.g. Cloudflare, Route 53).", "effort": "low", "time": "1 hour",
    },
    "server_response_time": {
        "name": "Server Response Time", "description": "Time to first server response",
        "details": "Time for the server to start responding.",
        "impact": "Slow server response delays all content loading.",
        "range": "Good: < 200ms | Poor: > 500ms",
        "threshold_good": 200, "threshold_poor": 500,
        "category": "infrastructure", "priority": "high",
        "action": "Optimize server config, add caching.", "effort": "medium", "time": "2-4 hours",
    },
    "cdn_detected": {
        "name": "CDN Usage", "description": "Content Delivery Network presence",
        "details": "Whether site uses a CDN.",
        "impact": "CDNs dramatically improve global load speeds.",
        "range": "Good: Present | Poor: Missing",
        "category": "infrastructure", "priority": "high",
        "action": "Implement a CDN (Cloudflare, Fastly, CloudFront).", "effort": "medium", "time": "2-4 hours",
    },
    "compression": {
        "name": "Compression Enabled", "description": "Gzip/Brotli compression",
        "details": "Whether responses are compressed.",
        "impact": "Compression reduces transfer size by 60-80%.",
        "range": "Good: Enabled | Poor: Missing",
        "category": "infrastructure", "priority": "high",
        "action": "Enable Gzip or Brotli compression.", "effort": "low", "time": "30 minutes",
    },
    "http2_enabled": {
        "name": "HTTP/2 Enabled", "description": "HTTP/2 protocol support",
        "details": "Whether the server supports HTTP/2.",
        "impact": "HTTP/2 multiplexing significantly improves load time.",
        "range": "Good: Enabled | Poor: HTTP/1.1",
        "category": "infrastructure", "priority": "medium",
        "action": "Enable HTTP/2 on your web server.", "effort": "low", "time": "1 hour",
    },
    "hsts_preload": {
        "name": "HSTS Preload", "description": "HSTS preload list inclusion",
        "details": "Whether the site is on the HSTS preload list.",
        "impact": "Guarantees HTTPS even on first visit.",
        "range": "Good: Included | Poor: Not included",
        "category": "infrastructure", "priority": "low",
        "action": "Submit to HSTS preload list at hstspreload.org.", "effort": "low", "time": "30 minutes",
    },
    "tls13_enabled": {
        "name": "TLS 1.3 Support", "description": "TLS 1.3 protocol",
        "details": "Whether TLS 1.3 is supported.",
        "impact": "TLS 1.3 is faster and more secure than older versions.",
        "range": "Good: Enabled | Poor: Missing",
        "category": "infrastructure", "priority": "medium",
        "action": "Enable TLS 1.3 on your web server.", "effort": "low", "time": "30 minutes",
    },
    "ipv6_support": {
        "name": "IPv6 Support", "description": "IPv6 connectivity",
        "details": "Whether the site is accessible over IPv6.",
        "impact": "Future-proofing and faster connections for IPv6 users.",
        "range": "Good: Supported | Poor: IPv4 only",
        "category": "infrastructure", "priority": "low",
        "action": "Enable IPv6 on your DNS and server.", "effort": "medium", "time": "1-2 hours",
    },

    # ── SEO ───────────────────────────────────────────────────
    "title_present": {
        "name": "Title Tag", "description": "Page title presence",
        "details": "Whether the page has a <title> tag.",
        "impact": "Critical for search engine rankings and CTR.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "critical",
        "action": "Add a unique, descriptive title tag to every page.", "effort": "low", "time": "10 minutes",
    },
    "title_length": {
        "name": "Title Length", "description": "Characters in title tag",
        "details": "Number of characters in the title tag.",
        "impact": "Titles outside 50-60 chars get truncated in SERPs.",
        "range": "Good: 50-60 chars | Poor: <30 or >70",
        "good_min": 50, "good_max": 60,
        "category": "seo", "priority": "high",
        "action": "Optimize title length to 50-60 characters.", "effort": "low", "time": "15 minutes",
    },
    "meta_description_present": {
        "name": "Meta Description", "description": "Meta description presence",
        "details": "Whether the page has a meta description.",
        "impact": "Influences click-through rates from search results.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "high",
        "action": "Add compelling meta descriptions (150-160 chars).", "effort": "low", "time": "15 minutes",
    },
    "viewport_present": {
        "name": "Viewport Meta Tag", "description": "Viewport configuration",
        "details": "Whether the viewport meta tag is present.",
        "impact": "Essential for mobile responsiveness.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "critical",
        "action": "Add <meta name='viewport' content='width=device-width, initial-scale=1'>.", "effort": "low", "time": "5 minutes",
    },
    "lang_present": {
        "name": "Language Attribute", "description": "HTML lang attribute",
        "details": "Whether the <html> tag has a lang attribute.",
        "impact": "Helps search engines and screen readers identify language.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "critical",
        "action": "Add lang='en' (or appropriate code) to your <html> tag.", "effort": "low", "time": "5 minutes",
    },
    "h1_count": {
        "name": "H1 Headings", "description": "Number of H1 tags",
        "details": "Count of H1 heading tags on the page.",
        "impact": "Exactly one H1 helps search engines understand page topic.",
        "range": "Good: 1 | Poor: 0 or >1",
        "category": "seo", "priority": "high",
        "action": "Use exactly one H1 tag per page.", "effort": "low", "time": "15 minutes",
    },
    "alt_percentage": {
        "name": "Image Alt Text Coverage", "description": "% of images with alt text",
        "details": "Percentage of images that have alt attributes.",
        "impact": "Alt text improves accessibility and image SEO.",
        "range": "Good: > 90% | Poor: < 50%",
        "threshold_good": 90, "threshold_poor": 50,
        "category": "seo", "priority": "medium",
        "action": "Add descriptive alt text to all images.", "effort": "medium", "time": "1-3 hours",
    },
    "schema_present": {
        "name": "Schema Markup", "description": "Structured data presence",
        "details": "Whether the page has schema.org structured data.",
        "impact": "Enables rich snippets in search results.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "high",
        "action": "Add relevant schema markup (Article, Product, FAQ, etc.).", "effort": "medium", "time": "2-4 hours",
    },
    "robots_exists": {
        "name": "Robots.txt", "description": "robots.txt file present",
        "details": "Whether a robots.txt file exists at the root.",
        "impact": "Controls search engine crawling of your site.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "medium",
        "action": "Create a robots.txt file.", "effort": "low", "time": "30 minutes",
    },
    "sitemap_exists": {
        "name": "XML Sitemap", "description": "sitemap.xml present",
        "details": "Whether a sitemap.xml file exists.",
        "impact": "Improves page discovery and indexing speed.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "high",
        "action": "Create and submit an XML sitemap to Google Search Console.", "effort": "low", "time": "1 hour",
    },
    "canonical_present": {
        "name": "Canonical Tag", "description": "Canonical URL tag",
        "details": "Whether a canonical link tag is present.",
        "impact": "Prevents duplicate content penalties.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "medium",
        "action": "Add <link rel='canonical'> to every page.", "effort": "low", "time": "30 minutes",
    },
    "og_tags_present": {
        "name": "Open Graph Tags", "description": "OG meta tags for social sharing",
        "details": "Whether Open Graph meta tags are present.",
        "impact": "Controls how content appears when shared on social media.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "medium",
        "action": "Add og:title, og:description, og:image tags.", "effort": "low", "time": "30 minutes",
    },
    "twitter_cards": {
        "name": "Twitter Card Tags", "description": "Twitter Card meta tags",
        "details": "Whether Twitter Card meta tags are present.",
        "impact": "Improves appearance when shared on Twitter/X.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "low",
        "action": "Add twitter:card, twitter:title, twitter:description tags.", "effort": "low", "time": "20 minutes",
    },
    "favicon_present": {
        "name": "Favicon", "description": "Site favicon",
        "details": "Whether a favicon is defined.",
        "impact": "Improves brand recognition in browser tabs.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "low",
        "action": "Add a favicon.ico and link tag.", "effort": "low", "time": "15 minutes",
    },
    "keywords_meta": {
        "name": "Keywords Meta Tag", "description": "Meta keywords tag",
        "details": "Whether a meta keywords tag is present.",
        "impact": "Ignored by modern search engines, but harmless.",
        "range": "Good: Present | Poor: Missing",
        "category": "seo", "priority": "low",
        "action": "Optional — modern SEO focus on content quality instead.", "effort": "low", "time": "10 minutes",
    },

    # ── Accessibility ─────────────────────────────────────────
    "lang_attribute": {
        "name": "HTML Language Attribute", "description": "lang on <html> tag",
        "details": "Whether the HTML tag has a lang attribute.",
        "impact": "Essential for screen readers to use correct pronunciation.",
        "range": "Good: Present | Poor: Missing",
        "category": "accessibility", "priority": "critical",
        "action": "Add lang attribute to <html> tag.", "effort": "low", "time": "5 minutes",
    },
    "aria_count": {
        "name": "ARIA Attributes", "description": "ARIA accessibility attributes",
        "details": "Whether the page uses ARIA attributes.",
        "impact": "Makes dynamic content accessible to screen reader users.",
        "range": "Good: >0 | Poor: 0",
        "category": "accessibility", "priority": "high",
        "action": "Add ARIA attributes to interactive elements.", "effort": "medium", "time": "2-4 hours",
    },
    "skip_link_present": {
        "name": "Skip Navigation Link", "description": "Skip to main content link",
        "details": "Whether the page has a skip navigation link.",
        "impact": "Critical for keyboard-only users.",
        "range": "Good: Present | Poor: Missing",
        "category": "accessibility", "priority": "high",
        "action": "Add a 'Skip to main content' link at the top of the page.", "effort": "low", "time": "30 minutes",
    },
    "alt_text_present": {
        "name": "Image Alt Text", "description": "Images with alt attributes",
        "details": "Whether all images have alt text.",
        "impact": "Essential for screen reader users.",
        "range": "Good: > 90% | Poor: < 50%",
        "category": "accessibility", "priority": "high",
        "action": "Add descriptive alt text to all meaningful images.", "effort": "medium", "time": "1-3 hours",
    },
    "form_labels": {
        "name": "Form Labels", "description": "Form inputs with labels",
        "details": "Whether form inputs have associated <label> elements.",
        "impact": "Essential for screen reader users filling forms.",
        "range": "Good: All labelled | Poor: Missing",
        "category": "accessibility", "priority": "high",
        "action": "Add <label> elements to all form fields.", "effort": "low", "time": "1-2 hours",
    },
    "color_contrast": {
        "name": "Color Contrast", "description": "Text/background contrast ratio",
        "details": "Estimated contrast between text and background.",
        "impact": "Low contrast makes text unreadable for visually impaired users.",
        "range": "Good: > 4.5:1 | Poor: < 3:1",
        "category": "accessibility", "priority": "high",
        "action": "Use a contrast checker and update low-contrast text.", "effort": "medium", "time": "2-4 hours",
    },
    "focus_visible": {
        "name": "Focus Indicators", "description": "Visible keyboard focus styles",
        "details": "Whether focused elements have visible outlines.",
        "impact": "Essential for keyboard navigation users.",
        "range": "Good: Visible | Poor: Hidden",
        "category": "accessibility", "priority": "high",
        "action": "Do not set outline:none — add visible :focus styles.", "effort": "low", "time": "1 hour",
    },
    "heading_structure": {
        "name": "Heading Structure", "description": "Logical heading hierarchy",
        "details": "Whether headings follow a logical order (h1→h2→h3).",
        "impact": "Screen reader users navigate by headings.",
        "range": "Good: Logical | Poor: Skipped/missing",
        "category": "accessibility", "priority": "medium",
        "action": "Use headings in sequential order without skipping levels.", "effort": "low", "time": "1 hour",
    },
    "aria_roles": {
        "name": "ARIA Roles", "description": "ARIA landmark roles",
        "details": "Whether the page uses ARIA role attributes.",
        "impact": "Helps screen readers understand page structure.",
        "range": "Good: Present | Poor: Missing",
        "category": "accessibility", "priority": "medium",
        "action": "Add role attributes to landmarks (main, nav, header, footer).", "effort": "low", "time": "1 hour",
    },
    "aria_labels": {
        "name": "ARIA Labels", "description": "ARIA label attributes",
        "details": "Whether interactive elements have aria-label or aria-labelledby.",
        "impact": "Provides accessible names for icon buttons and controls.",
        "range": "Good: Present | Poor: Missing",
        "category": "accessibility", "priority": "medium",
        "action": "Add aria-label to buttons/controls without visible text.", "effort": "low", "time": "1 hour",
    },
    "video_captions": {
        "name": "Video Captions", "description": "Captions on video content",
        "details": "Whether videos have captions or transcripts.",
        "impact": "Required for deaf/hard-of-hearing users.",
        "range": "Good: Present | Poor: Missing",
        "category": "accessibility", "priority": "medium",
        "action": "Add closed captions to all video content.", "effort": "high", "time": "4-8 hours",
    },
    "audio_transcripts": {
        "name": "Audio Transcripts", "description": "Transcripts for audio content",
        "details": "Whether audio elements have transcripts.",
        "impact": "Required for deaf/hard-of-hearing users.",
        "range": "Good: Present | Poor: Missing",
        "category": "accessibility", "priority": "medium",
        "action": "Add transcripts for all audio content.", "effort": "medium", "time": "2-4 hours",
    },
    "table_headers": {
        "name": "Table Headers", "description": "Tables with <th> headers",
        "details": "Whether data tables use <th> header cells.",
        "impact": "Screen readers use headers to describe table data.",
        "range": "Good: Present | Poor: Missing",
        "category": "accessibility", "priority": "medium",
        "action": "Add <th> elements with scope attributes to all data tables.", "effort": "low", "time": "1 hour",
    },
    "table_caption": {
        "name": "Table Captions", "description": "Tables with <caption>",
        "details": "Whether data tables have a <caption> element.",
        "impact": "Helps screen reader users understand table purpose.",
        "range": "Good: Present | Poor: Missing",
        "category": "accessibility", "priority": "low",
        "action": "Add <caption> to describe the purpose of each table.", "effort": "low", "time": "30 minutes",
    },
    "alt_text_quality": {
        "name": "Alt Text Quality", "description": "Descriptive alt text",
        "details": "Whether alt text is descriptive rather than generic.",
        "impact": "Generic alt text is useless for screen reader users.",
        "range": "Good: Descriptive | Poor: Generic",
        "category": "accessibility", "priority": "medium",
        "action": "Replace generic alt text like 'image' with descriptions.", "effort": "medium", "time": "1-2 hours",
    },

    # ── Business ──────────────────────────────────────────────
    "contact_info": {
        "name": "Contact Information", "description": "Business contact details",
        "details": "Whether contact information is visible on the page.",
        "impact": "Builds trust and enables customer communication.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "high",
        "action": "Add clear contact info (phone, email, address) to the site.", "effort": "low", "time": "30 minutes",
    },
    "cta_count": {
        "name": "Call-to-Action Buttons", "description": "Number of CTA elements",
        "details": "Count of call-to-action buttons and links.",
        "impact": "Clear CTAs are essential for conversions.",
        "range": "Good: 1-3 | Poor: 0 or >10",
        "good_min": 1, "good_max": 3,
        "category": "business", "priority": "medium",
        "action": "Add 1-3 prominent, action-oriented CTAs.", "effort": "low", "time": "1-2 hours",
    },
    "privacy_policy": {
        "name": "Privacy Policy", "description": "Privacy policy page",
        "details": "Whether a privacy policy link is present.",
        "impact": "Legal requirement in most jurisdictions; builds trust.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "high",
        "action": "Add a privacy policy page and link it in the footer.", "effort": "low", "time": "1 hour",
    },
    "terms_of_service": {
        "name": "Terms of Service", "description": "Terms of service page",
        "details": "Whether a terms of service link is present.",
        "impact": "Protects the business legally.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "medium",
        "action": "Add a terms of service page.", "effort": "low", "time": "1 hour",
    },
    "about_page": {
        "name": "About Page", "description": "About us page",
        "details": "Whether an about page is linked.",
        "impact": "Builds trust and tells the company story.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "medium",
        "action": "Create a comprehensive about page.", "effort": "low", "time": "1-2 hours",
    },
    "social_links": {
        "name": "Social Media Links", "description": "Links to social profiles",
        "details": "Whether links to social media profiles are present.",
        "impact": "Builds social proof and extends reach.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "low",
        "action": "Add links to your active social media profiles.", "effort": "low", "time": "30 minutes",
    },
    "trust_badges": {
        "name": "Trust Badges", "description": "Security/trust indicators",
        "details": "Whether trust badges (SSL, payment icons, etc.) are displayed.",
        "impact": "Increases conversion rates, especially at checkout.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "medium",
        "action": "Add relevant trust badges (SSL seal, payment icons).", "effort": "low", "time": "1 hour",
    },
    "testimonials": {
        "name": "Testimonials / Reviews", "description": "Social proof content",
        "details": "Whether testimonials or reviews are present.",
        "impact": "Social proof can increase conversions by 15-30%.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "medium",
        "action": "Add customer testimonials or review integrations.", "effort": "medium", "time": "2-4 hours",
    },
    "pricing_visible": {
        "name": "Pricing Visibility", "description": "Pricing information present",
        "details": "Whether pricing or a link to pricing is present.",
        "impact": "Hidden pricing increases bounce rates.",
        "range": "Good: Visible | Poor: Hidden",
        "category": "business", "priority": "medium",
        "action": "Make pricing clear and easy to find.", "effort": "low", "time": "1-2 hours",
    },
    "faq_page": {
        "name": "FAQ Page", "description": "Frequently asked questions",
        "details": "Whether an FAQ page is linked.",
        "impact": "Reduces support load and improves SEO.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "low",
        "action": "Create an FAQ page addressing common questions.", "effort": "medium", "time": "2-3 hours",
    },
    "blog_present": {
        "name": "Blog / News Section", "description": "Blog or news content",
        "details": "Whether a blog or news section is linked.",
        "impact": "Fresh content improves SEO and builds authority.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "low",
        "action": "Start a blog with regular, relevant content.", "effort": "high", "time": "ongoing",
    },
    "newsletter": {
        "name": "Newsletter / Email Signup", "description": "Email capture form",
        "details": "Whether an email signup form is present.",
        "impact": "Email lists are a high-ROI marketing channel.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "low",
        "action": "Add a newsletter signup form.", "effort": "medium", "time": "2-4 hours",
    },
    "live_chat": {
        "name": "Live Chat", "description": "Live chat widget",
        "details": "Whether a live chat or chatbot is present.",
        "impact": "Live chat can increase conversions by 20-40%.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "low",
        "action": "Integrate a live chat tool (Intercom, Drift, Tawk.to).", "effort": "medium", "time": "2-4 hours",
    },
    "return_policy": {
        "name": "Return / Refund Policy", "description": "Return/refund policy page",
        "details": "Whether a return or refund policy is linked.",
        "impact": "Required for e-commerce trust and legal compliance.",
        "range": "Good: Present | Poor: Missing",
        "category": "business", "priority": "medium",
        "action": "Add a clear return/refund policy page.", "effort": "low", "time": "1 hour",
    },
    "cta_visibility": {
        "name": "CTA Visibility", "description": "Prominence of CTAs",
        "details": "Whether CTAs are clearly visible above the fold.",
        "impact": "Above-fold CTAs dramatically improve conversion rates.",
        "range": "Good: Visible | Poor: Hidden",
        "category": "business", "priority": "medium",
        "action": "Ensure your main CTA is visible without scrolling.", "effort": "low", "time": "1-2 hours",
    },

    # ── Lighthouse Full Categories ────────────────────────────
    "lh_accessibility_score": {
        "name": "Lighthouse Accessibility", "description": "Lighthouse accessibility audit score",
        "details": "Automated accessibility checks from Lighthouse covering ARIA, contrast, labels, and more.",
        "impact": "Low score means users with disabilities cannot use your site.",
        "range": "Good: > 90 | Poor: < 50",
        "threshold_good": 90, "threshold_poor": 50,
        "category": "accessibility", "priority": "high",
        "action": "Fix issues listed in the Lighthouse accessibility report.", "effort": "medium", "time": "4-8 hours",
    },
    "lh_best_practices_score": {
        "name": "Lighthouse Best Practices", "description": "Lighthouse best practices score",
        "details": "Checks for HTTPS, modern APIs, browser errors, and security best practices.",
        "impact": "Low score indicates technical debt and potential security risks.",
        "range": "Good: > 90 | Poor: < 50",
        "threshold_good": 90, "threshold_poor": 50,
        "category": "lighthouse", "priority": "high",
        "action": "Review and fix issues in the Lighthouse best practices audit.", "effort": "medium", "time": "2-6 hours",
    },
    "lh_pwa_score": {
        "name": "Lighthouse PWA Score", "description": "Progressive Web App readiness",
        "details": "How well the site meets PWA standards — offline support, manifest, service worker.",
        "impact": "PWA features enable add-to-homescreen, offline mode, and push notifications.",
        "range": "Good: > 90 | Poor: < 50",
        "threshold_good": 90, "threshold_poor": 50,
        "category": "lighthouse", "priority": "medium",
        "action": "Add a web app manifest, service worker, and HTTPS to improve PWA score.", "effort": "high", "time": "8-16 hours",
    },
    "lh_seo_score": {
        "name": "Lighthouse SEO Score", "description": "Lighthouse SEO audit score",
        "details": "Lighthouse checks for crawlability, mobile-friendliness, and meta tags.",
        "impact": "Low score directly reduces search engine visibility.",
        "range": "Good: > 90 | Poor: < 50",
        "threshold_good": 90, "threshold_poor": 50,
        "category": "seo", "priority": "high",
        "action": "Fix all issues flagged in the Lighthouse SEO audit.", "effort": "low", "time": "1-3 hours",
    },

    # ── Mobile vs Desktop ─────────────────────────────────────
    "mobile_performance_score": {
        "name": "Mobile Performance Score", "description": "PageSpeed score on mobile",
        "details": "Composite performance score measured on a simulated mobile device.",
        "impact": "Over 60% of web traffic is mobile — poor mobile scores lose users.",
        "range": "Good: > 90 | Poor: < 50",
        "threshold_good": 90, "threshold_poor": 50,
        "category": "performance", "priority": "critical",
        "action": "Optimise images, reduce JavaScript, and use lazy loading for mobile.", "effort": "medium", "time": "4-8 hours",
    },
    "desktop_performance_score": {
        "name": "Desktop Performance Score", "description": "PageSpeed score on desktop",
        "details": "Composite performance score measured on a simulated desktop device.",
        "impact": "Desktop users expect near-instant load times.",
        "range": "Good: > 90 | Poor: < 50",
        "threshold_good": 90, "threshold_poor": 50,
        "category": "performance", "priority": "high",
        "action": "Reduce render-blocking resources and optimise server response time.", "effort": "medium", "time": "2-4 hours",
    },
    "mobile_desktop_gap": {
        "name": "Mobile/Desktop Score Gap", "description": "Performance gap between mobile and desktop",
        "details": "Absolute difference in performance scores between mobile and desktop.",
        "impact": "A large gap means mobile users get a significantly worse experience.",
        "range": "Good: < 10 points | Poor: > 30 points",
        "threshold_good": 10, "threshold_poor": 30,
        "category": "performance", "priority": "high",
        "action": "Identify mobile-specific bottlenecks using the mobile Lighthouse report.", "effort": "medium", "time": "3-6 hours",
    },

    # ── Broken Links ──────────────────────────────────────────
    "broken_links_count": {
        "name": "Broken Links", "description": "Number of broken links on the page",
        "details": "Count of internal and external links returning 4xx/5xx or timing out.",
        "impact": "Broken links hurt SEO, damage credibility, and frustrate users.",
        "range": "Good: 0 | Poor: > 5",
        "threshold_good": 0, "threshold_poor": 5,
        "category": "seo", "priority": "high",
        "action": "Fix or remove all broken links found in the report.", "effort": "medium", "time": "1-3 hours",
    },

    # ── Carbon / Green ────────────────────────────────────────
    "carbon_grams": {
        "name": "CO₂ Per Page View", "description": "Estimated carbon emissions per visit",
        "details": "Grams of CO₂ produced per page view, estimated from page weight and energy mix.",
        "impact": "High carbon sites are increasingly penalised by eco-conscious users and regulations.",
        "range": "Good: < 0.5g | Poor: > 2g",
        "threshold_good": 0.5, "threshold_poor": 2.0,
        "category": "green", "priority": "medium",
        "action": "Reduce page weight, use green hosting, optimise images and fonts.", "effort": "medium", "time": "2-8 hours",
    },
    "carbon_cleaner_than": {
        "name": "Cleaner Than % of Web", "description": "Percentile vs all tested websites",
        "details": "What percentage of websites this site is cleaner than, per Website Carbon API.",
        "impact": "Shows relative environmental performance vs the broader web.",
        "range": "Good: > 75% | Poor: < 25%",
        "threshold_good": 75, "threshold_poor": 25,
        "category": "green", "priority": "low",
        "action": "Reduce page size and switch to a green hosting provider.", "effort": "medium", "time": "varies",
    },
}
